version: '3'

services:

 feedcollector:
  image: ruby:slim
  restart: on-failure
  container_name: feedcollector
  volumes:
    - data:/data
    - ./:/app:ro
  working_dir: "/app"
  entrypoint: ruby
  command: "/app/feedcollector.rb -f config-docker.yml"

volumes:
  data:
